### ISSUE TITLE
Can I run it in real time using webcam ? 

### ISSUE THREAD

**Issue by aalzooke** [see--/P12-Semantic-Segmentation#4]
Please let me know how can i run it using my laptop camera?
Thank you

**Comment by see--** [comment]
You could modify this script: https://github.com/see--/P12-Semantic-Segmentation/blob/master/src/dump_predictions.py. More specifically: Put your images from the webcam [here](https://github.com/see--/P12-Semantic-Segmentation/blob/master/src/dump_predictions.py#L33). You can then show the images instead of writing them to disk.

**Comment by aalzooke** [comment]
Can you please write another script which can run it in real time? 
Thank you

**Comment by see--** [comment]
I don't have a use case for this – I just see myself with my webcam :). Please feel free to submit a pull request with the webcam demo.
